-- 1. What is the total number of products in each category?
SELECT product_category_id, COUNT(*) AS total_products 
FROM products 
GROUP BY product_category_id;

-- 2. List the products with prices lower than the average price in their category.
SELECT product_name, product_price, product_category_id 
FROM products 
WHERE product_price < (SELECT AVG(product_price) FROM products WHERE product_category_id = products.product_category_id);

-- 3. What is the average price of products in each category?
SELECT product_category_id, AVG(product_price) AS avg_product_price 
FROM products 
GROUP BY product_category_id;

-- 4. How many products are in each price range (e.g., 0-100, 101-500, 501-1000)?
SELECT 
    CASE 
        WHEN product_price BETWEEN 0 AND 100 THEN '0-100'
        WHEN product_price BETWEEN 101 AND 500 THEN '101-500'
        WHEN product_price BETWEEN 501 AND 1000 THEN '501-1000'
        ELSE '1001+' 
    END AS price_range,
    COUNT(*) AS total_products
FROM products
GROUP BY price_range;

-- 5. List the products with the highest price.
SELECT product_name, product_price 
FROM products 
WHERE product_price = (SELECT MAX(product_price) FROM products);

-- 6. What is the total revenue generated by each product category (product_price * total quantity sold)?
SELECT product_category_id, SUM(product_price) AS total_revenue 
FROM products 
GROUP BY product_category_id;

-- 7. Which products have a price greater than $1000?
SELECT product_name, product_price 
FROM products 
WHERE product_price > 1000;

-- 8. How many products belong to each product category?
SELECT product_category_id, COUNT(*) AS total_products 
FROM products 
GROUP BY product_category_id;

-- 9. What is the lowest priced product in each category?
SELECT product_category_id, MIN(product_price) AS min_product_price 
FROM products 
GROUP BY product_category_id;

-- 10. List all products with a price range between $500 and $1500.
SELECT product_name, product_price 
FROM products 
WHERE product_price BETWEEN 500 AND 1500;

